### ISSUE TITLE
This violates @YOURsammich 's patent on socket.io forks. 

### ISSUE THREAD

**Issue by LandonPowell** [Getindor/-c-2.0#1]
Watch out or he might start stealing your regex. :100: :clap: :clap: :clap:

**Comment by makeamericagreatagain** [comment]
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂
